name: Android Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.7-jdk17
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Release APK
        run: gradle assembleRelease

      - name: Upload compiled APK
        uses: actions/upload-artifact@v4
        with:
          name: Release_APK
          path: app/build/outputs/apk/release/*.apk
