name: Android Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.7-jdk17
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build release APK
        run: gradle assembleRelease

      - name: Upload output APK
        uses: actions/upload-artifact@v4
        with:
          name: Compiled_APK
          path: app/build/outputs/apk/release/*.apk
